### ISSUE TITLE
How to add <!DOCTYPE html> by (response/xexpr) ?

### ISSUE THREAD

**Issue by ChengxiX** [racket/web-server#114]
How to add <!DOCTYPE html> by (response/xexpr) ?
I cannot do it by `(response/xexpr '(!DOCTYPE html (html ...)))` or `(response/xexpr '(!DOCTYPE ((html)) (html ...)))`

**Comment by jeapostrophe** [comment]
That's what the `#:preamble` keyword is for

**Comment by ChengxiX** [comment]
Thank you!

**Comment by ChengxiX** [comment]
No thanks i got it
