### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by aboutkrin** [racket/web-server#12]
when I enter a number, it went through the second url but it still show up "Enter the First number to add:". Then when I type another number and hit submit, it won't go to display-sum.

**Comment by jeapostrophe** [comment]
What code are you trying?

**Comment by aboutkrin** [comment]
I went through your example file, the file called add-dispatch.rkt seems not working properly. The dispatch rule stuck on the else statement and it generate the URL but does’t call right function (get-second and display-sum). I tried to fix it but no luck. Could you please help me out?
Thank you

`Code:

#lang racket/base
(require web-server/servlet)

(define (extract-number req)
 (string->number
  (extract-binding/single
   'number
   (request-bindings req))))

; build-request-page : str str -> response
(define (build-request-page which-number k-url)
 (response/xexpr
  `(html (head (title "Enter a Number to Add"))
         (body ([bgcolor "white"])
               (form ([action ,k-url] [method "post"])
                     "Enter the " ,which-number " number to add: "
                     (input ([type "text"] [name "number"] [value ""]))
                     (input ([type "submit"] [name "enter"] [value "Enter"])))))))

(define (get-first req)
 (build-request-page "First" (add-url get-second)))

(define (get-second req)
 (define fst (extract-number req))
 (build-request-page "Second" (add-url display-sum fst)))

(define (display-sum req fst)
 (define snd (extract-number req))
 (response/xexpr
  `(html (head (title "Sum"))
         (body ([bgcolor "white"])
               (p "The answer is "
                  ,(number->string (+ fst snd)))))))

(define-values (start add-url)
 (dispatch-rules
  [("get-second") get-second]
  [("display-sum" (integer-arg)) display-sum]
  [else get-first]))

(serve/dispatch start)`

**Comment by jeapostrophe** [comment]
Your example uses `dispatch-rules` and the default method for a dispatch rules case is "GET", yet your form generates "POST" requests, so the POST request is not handled by the `get-second` or `display-sum` handlers. And if you were to have used `[("") get-first]` rather than `[else get-first]`, then it wouldn't be handled by any case.

You meant to write:

```
(dispatch-rules
   [("get-second") #:method "post" get-second]
   [("display-sum" (integer-arg)) #:method "post"  display-sum]
   [else get-first])
```

Or to have not used a POST in the form.
