### ISSUE TITLE
plt-web-server --ssl does not actually create SSL listener.

### ISSUE THREAD

**Issue by e45lee** [racket/web-server#13]
Sometime between Racket 6.0 and 6.3 `plt-web-server --ssl` stops creating a server that accepts SSL connections.  On accepting an SSL connection, read-request errors out with malformed request: 

read-request: malformed request ��W+���)e�┼!��ʟԾ^��)4�3�E��� ʷˤ!�H~��q����7ɍ#)<ȁ����]Fr�J��$�#�
  context...:
   /usr/racket/share/pkgs/web-server-lib/web-server/private/util.rkt:37:0: network-error
   ...ow-val-first.rkt:302:18
   /usr/racket/share/pkgs/web-server-lib/web-server/http/request.rkt:31:0
   /usr/racket/share/pkgs/web-server-lib/web-server/private/dispatch-server-with-connect-unit.rkt:131:8

**Comment by jeapostrophe** [comment]
Thank you, it should be fixed now. However, I do not recommend using `plt-web-server`. I recommend upgrading to use `serve/servlet`.

**Comment by shriram** [comment]
Perhaps then the docs on [using the server with HTTPS](https://docs.racket-lang.org/web-server-internal/Troubleshooting_and_Tips.html#%28part._faq~3ahttps%29) should not tell people to use `plt-web-server`?

<img width="279" alt="image" src="https://github.com/racket/web-server/assets/75030/3a464e73-7527-4061-a8b1-056689446817">
