### ISSUE TITLE
print and display silenced

### ISSUE THREAD

**Issue by rightfold** [racket/web-server#14]
When I try to print or display something in a servlet, I don't see it in my terminal.

```
(serve/servlet (λ (req) (print req) (response/xexpr `(html))))
```

Why is this? And if it's intended, it should be documented.

**Comment by jeapostrophe** [comment]
Can you elaborate how you are running it? I just tested it on Linux and OS X with this program:

```
#lang racket/base
(require web-server/servlet-env web-server/http)
(serve/servlet (λ (req) (print req) (response/xexpr `(html))))
```

And got the expected result.

**Comment by jessealama** [comment]
I propose closing this ticket. It’s been three years, and the OP hasn’t responded.

**Comment by rightfold** [comment]
I agree!
