### ISSUE TITLE
Fix regexp in servlet tester

### ISSUE THREAD

**Issue by dmitry-chmerev** [racket/web-server#27]
The `htmxl` function in `web-server-lib/web-server/test.rkt` splits a response into headers and body parts with regexp `^(.+)\r\n\r\n(.*)$`. If the body part contains '\r\n\r\n', the first matching group takes a piece of body as `+` is greedy quantifier. Please replace the regexp with `^(.+?)\r\n\r\n(.*)$`

**Comment by jeapostrophe** [comment]
Can you give an example where this causes a problem? I'd like to add a regsion test

**Comment by dmitry-chmerev** [comment]
I don't think my racket experience allows me to write such tests, bear with me
bad-body.rkt:
```racket
#lang racket/base
(require web-server/servlet)

(provide index)

(define (index request)
  (response
    200 #"OK"
    (current-seconds)
    #f '()
    (lambda (out)
      (write-bytes #"<html>bad\r\n\r\nbody</html>" out))))
```
bad-body-test.rkt
```racket
#lang racket/base
(require web-server/test
         rackunit
         net/url
         web-server/http
         racket/promise
         "bad-body.rkt")

(define (url->request u)
  (make-request #"GET" (string->url u) '()
                (delay '()) #f "127.0.0.1" 8080 "127.0.0.1"))

(check-not-exn
  (lambda ()
    (let [(tester (make-servlet-tester index))]
      (tester (url->request "")))))
```

**Comment by jeapostrophe** [comment]
Thank you! I fixed it and used your test.
