### ISSUE TITLE
Web Server does not time out SSL connections that are stuck negotiating the SSL tunnel.

### ISSUE THREAD

**Issue by e45lee** [racket/web-server#4]
When the web server accepts a SSL connection, the web server (in its main loop):
  - accepts the connection
  - negotiates the SSL tunnel, without any timeout on this process.
  - then creates a new thread to handle the connection.

This has the problem that a malicious client could just effectively hang the web server by opening a connection to it while not negotiating the SSL connection.

Steps to reproduce:
 (in one terminal) plt-web-server --ssl -port 5000
 (in another terminal) run telnet localhost 5000, do nothing.
 (in another terminal) openssl s_client --connect localhost:5000 (this will hang until you close telnet)

**Comment by mflatt** [comment]
This problem is fixed for the next release. You could try a snapshot from http://www.cs.utah.edu/plt/snapshots/
Thanks for the report!
