### ISSUE TITLE
Contract on make-id-cookie should accept byte-strings

### ISSUE THREAD

**Issue by LiberalArtist** [racket/web-server#74]
@soegaard reported on Slack that the contract on `make-id-cookie` currently requires the name and value arguments to be given as strings, so this program fails:
```racket
#lang racket

(require web-server/http/id-cookie
         racket/random)

(make-id-cookie #"aname" #"avalue"
                #:key (crypto-random-bytes 128))
```

All other cookie-constructing functions permissively accept byte-strings for names and values (converting them with `bytes->string/utf-8`), and it seems like `make-id-cookie` should, too—I probably just missed it after I figured out https://github.com/RenaissanceBug/racket-cookies/commit/c745ee51e9a4914d232380abe65332d91d88f7f8. I will try to make a PR soon.

**Comment by LiberalArtist** [comment]
While working on a patch, I believe I found another bug. In this code: https://github.com/racket/web-server/blob/245047b620af75564ea14ac5d8ca9cae46d0ed04/web-server-lib/web-server/http/id-cookie.rkt#L83-L87
In https://github.com/racket/web-server/commit/a5135d5f1c96a21c55c704fa4bf56a4cc607307f, I believe @jeapostrophe should have changed `-3` to `-1` when he supplied `#""` to `base64-encode` for the newline instead of the default `#"\r\n"`.

A base64-encoded SHA-1 is always 28 bytes long, including exactly one `=` at the end for padding: since the length is fixed, we can drop the padding and return 27 bytes from `mac`. Right now, we are also dropping 2 significant digits of the SHA-1 hash.

I think this should be fixed and plan to include it in this patch. However, people's existing id cookies created with the current version of the library will not validate using a fixed version. I think the potential security implications outweigh the breakage, but I'm open to other opinions.

**Comment by LiberalArtist** [comment]
If it seems necessary, one option would be to add a function `unverified-id-cookie?`. I think it would be like `valid-id-cookie?`, but `#:key` would be optional and default to `#f`. If the key is `#f`, it would just check the name and timeout and not try to verify the digest. beyond checking that it syntactically could have been generated by some version of this library (i.e. it is 25 or 27 base64 digits). Alternatively, if you supply a key, it would check the digest but allow it to be two digits short.

That would let programmers make their own decisions about how to handle their existing id cookies. But, personally, I don't feel a need for such a function.

**Comment by jeapostrophe** [comment]
You should just change the `-3` to a `-1`. It was simply a mistake.
