### ISSUE TITLE
Test occasionally fails

### ISSUE THREAD

**Issue by samth** [racket/web-server#88]
http://drdr.racket-lang.org/54239/cs/racket/share/pkgs/web-server-test/tests/web-server/run-all-tests.rkt

This particular test has been failing occasionally, but seemingly only on Racket CS.

```
--------------------
Connection Manager > Internal > Web Server > Extend timer
FAILURE
name:       check-true
location:   private/connection-manager-test.rkt:51:4
params:     '(#f)
--------------------
```

**Comment by jessealama** [comment]
Thanks for bringing this up. I've noticed that, too. I recently did some work and was puzzled that the CS pipeline would fail sometimes, but pass at other times.

**Comment by samth** [comment]
I have been unable to reproduce this myself, so if anyone manages to, that would be helpful.

**Comment by samth** [comment]
I managed to reproduce this with the following command which runs 30 copies of the test in parallel:

```
parallel -j 100 -i racocs test  run-all-tests.rkt -- a b c d e f a b c d e f a b c d e f a b c d e f a b c d e f
```

**Comment by samth** [comment]
I also see some other (probably related) failures with that command:

```
                                                                              
Connection Manager > Internal > Web Server > Output closed                                               
FAILURE                                                                                                  
name:       check-true                                                                                   
location:   private/connection-manager-test.rkt:29:4                                                     
params:     '(#f)                           
```

**Comment by jessealama** [comment]
@LiberalArtist might this be related to the new safety limits feature?
